/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpaceActivationRouteImport } from './routes/space-activation'
import { Route as ProductServicesRouteImport } from './routes/product-services'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductServicesProductIdRouteImport } from './routes/product-services.$productId'

const SpaceActivationRoute = SpaceActivationRouteImport.update({
  id: '/space-activation',
  path: '/space-activation',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductServicesRoute = ProductServicesRouteImport.update({
  id: '/product-services',
  path: '/product-services',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductServicesProductIdRoute =
  ProductServicesProductIdRouteImport.update({
    id: '/$productId',
    path: '/$productId',
    getParentRoute: () => ProductServicesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/product-services': typeof ProductServicesRouteWithChildren
  '/space-activation': typeof SpaceActivationRoute
  '/product-services/$productId': typeof ProductServicesProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/product-services': typeof ProductServicesRouteWithChildren
  '/space-activation': typeof SpaceActivationRoute
  '/product-services/$productId': typeof ProductServicesProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/product-services': typeof ProductServicesRouteWithChildren
  '/space-activation': typeof SpaceActivationRoute
  '/product-services/$productId': typeof ProductServicesProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/product-services'
    | '/space-activation'
    | '/product-services/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/product-services'
    | '/space-activation'
    | '/product-services/$productId'
  id:
    | '__root__'
    | '/'
    | '/product-services'
    | '/space-activation'
    | '/product-services/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProductServicesRoute: typeof ProductServicesRouteWithChildren
  SpaceActivationRoute: typeof SpaceActivationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/space-activation': {
      id: '/space-activation'
      path: '/space-activation'
      fullPath: '/space-activation'
      preLoaderRoute: typeof SpaceActivationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-services': {
      id: '/product-services'
      path: '/product-services'
      fullPath: '/product-services'
      preLoaderRoute: typeof ProductServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-services/$productId': {
      id: '/product-services/$productId'
      path: '/$productId'
      fullPath: '/product-services/$productId'
      preLoaderRoute: typeof ProductServicesProductIdRouteImport
      parentRoute: typeof ProductServicesRoute
    }
  }
}

interface ProductServicesRouteChildren {
  ProductServicesProductIdRoute: typeof ProductServicesProductIdRoute
}

const ProductServicesRouteChildren: ProductServicesRouteChildren = {
  ProductServicesProductIdRoute: ProductServicesProductIdRoute,
}

const ProductServicesRouteWithChildren = ProductServicesRoute._addFileChildren(
  ProductServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProductServicesRoute: ProductServicesRouteWithChildren,
  SpaceActivationRoute: SpaceActivationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
