/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TechnologyRouteImport } from './routes/technology'
import { Route as SpaceActivationRouteImport } from './routes/space-activation'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductServicesIndexRouteImport } from './routes/product-services.index'
import { Route as CaseStudiesIndexRouteImport } from './routes/case-studies.index'
import { Route as ProductServicesProductIdRouteImport } from './routes/product-services.$productId'
import { Route as CaseStudiesSlugRouteImport } from './routes/case-studies.$slug'

const TechnologyRoute = TechnologyRouteImport.update({
  id: '/technology',
  path: '/technology',
  getParentRoute: () => rootRouteImport,
} as any)
const SpaceActivationRoute = SpaceActivationRouteImport.update({
  id: '/space-activation',
  path: '/space-activation',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductServicesIndexRoute = ProductServicesIndexRouteImport.update({
  id: '/product-services/',
  path: '/product-services/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesIndexRoute = CaseStudiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CaseStudiesRoute,
} as any)
const ProductServicesProductIdRoute =
  ProductServicesProductIdRouteImport.update({
    id: '/product-services/$productId',
    path: '/product-services/$productId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CaseStudiesSlugRoute = CaseStudiesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CaseStudiesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/space-activation': typeof SpaceActivationRoute
  '/technology': typeof TechnologyRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/product-services/$productId': typeof ProductServicesProductIdRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
  '/product-services/': typeof ProductServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/space-activation': typeof SpaceActivationRoute
  '/technology': typeof TechnologyRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/product-services/$productId': typeof ProductServicesProductIdRoute
  '/case-studies': typeof CaseStudiesIndexRoute
  '/product-services': typeof ProductServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/space-activation': typeof SpaceActivationRoute
  '/technology': typeof TechnologyRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/product-services/$productId': typeof ProductServicesProductIdRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
  '/product-services/': typeof ProductServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/case-studies'
    | '/space-activation'
    | '/technology'
    | '/case-studies/$slug'
    | '/product-services/$productId'
    | '/case-studies/'
    | '/product-services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/space-activation'
    | '/technology'
    | '/case-studies/$slug'
    | '/product-services/$productId'
    | '/case-studies'
    | '/product-services'
  id:
    | '__root__'
    | '/'
    | '/case-studies'
    | '/space-activation'
    | '/technology'
    | '/case-studies/$slug'
    | '/product-services/$productId'
    | '/case-studies/'
    | '/product-services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaseStudiesRoute: typeof CaseStudiesRouteWithChildren
  SpaceActivationRoute: typeof SpaceActivationRoute
  TechnologyRoute: typeof TechnologyRoute
  ProductServicesProductIdRoute: typeof ProductServicesProductIdRoute
  ProductServicesIndexRoute: typeof ProductServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/technology': {
      id: '/technology'
      path: '/technology'
      fullPath: '/technology'
      preLoaderRoute: typeof TechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/space-activation': {
      id: '/space-activation'
      path: '/space-activation'
      fullPath: '/space-activation'
      preLoaderRoute: typeof SpaceActivationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-services/': {
      id: '/product-services/'
      path: '/product-services'
      fullPath: '/product-services/'
      preLoaderRoute: typeof ProductServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/': {
      id: '/case-studies/'
      path: '/'
      fullPath: '/case-studies/'
      preLoaderRoute: typeof CaseStudiesIndexRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/product-services/$productId': {
      id: '/product-services/$productId'
      path: '/product-services/$productId'
      fullPath: '/product-services/$productId'
      preLoaderRoute: typeof ProductServicesProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/$slug': {
      id: '/case-studies/$slug'
      path: '/$slug'
      fullPath: '/case-studies/$slug'
      preLoaderRoute: typeof CaseStudiesSlugRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
  }
}

interface CaseStudiesRouteChildren {
  CaseStudiesSlugRoute: typeof CaseStudiesSlugRoute
  CaseStudiesIndexRoute: typeof CaseStudiesIndexRoute
}

const CaseStudiesRouteChildren: CaseStudiesRouteChildren = {
  CaseStudiesSlugRoute: CaseStudiesSlugRoute,
  CaseStudiesIndexRoute: CaseStudiesIndexRoute,
}

const CaseStudiesRouteWithChildren = CaseStudiesRoute._addFileChildren(
  CaseStudiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaseStudiesRoute: CaseStudiesRouteWithChildren,
  SpaceActivationRoute: SpaceActivationRoute,
  TechnologyRoute: TechnologyRoute,
  ProductServicesProductIdRoute: ProductServicesProductIdRoute,
  ProductServicesIndexRoute: ProductServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
